services:
  kong:
    image: kong:latest
    container_name: kong
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/kong.yml"
    volumes:
      - ./kong/kong.yml:/usr/local/kong/kong.yml
    networks:
      - my-network
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admindatabase
      POSTGRES_PASSWORD: admindatabase
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    restart: always
    networks:
      - my-network
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    restart: always
    networks:
      - my-network
  kafka:
    image: apache/kafka:latest
    container_name: broker
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - my-network

  kafka-productor:
    build:
      context: ./kafka-productor
      dockerfile: Dockerfile
    container_name: kafka-productor
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8090:8090"
    networks:
      - my-network

  kafka-consumer:
    build:
      context: ./kafka-consumer
      dockerfile: Dockerfile
    container_name: kafka-consumer
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8070:8070"
    networks:
      - my-network

  auth-api:
    build:
      context: ./Auth0
      dockerfile: Dockerfile
    container_name: auth0
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Auth0__Domain=https://dev-q7eednrlae4yxvel.us.auth0.com/
      - Auth0__Audience=https://auth0APIKevin
      - Auth0__client_id=Dcqawg99cWzahtkyavoY5nC3uq35aUDt
      - Auth0__client_secret =60YCBP0JzvzmJr2qAHkOiF2yGdDCsgyBqYj3dKEgrBLtBaHZunnchbVi7kIMaE7Z
      - Auth0__grant_type=client_credentials
      - Auth0__kafkaProductor=http://kafka-productor:8090/api/kafka/send
      - ASPNETCORE_PORT=8082
    ports:
      - "8082:8082"
    networks:
      - my-network
  api-gateway:
    build: ./api_gateway/gateway
    ports:
      - "4000:4000"
    environment:
      DB_HOST: 209.94.59.49
      DB_USER: admindatabase
      DB_PASSWORD: admindatabase
      DB_NAME: mydatabase
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
