version: '3.8'

services:
  graphql-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: graphql-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GRPC_COURSE_URL=grpc-server:8080
      - GRPC_STUDENT_URL=grpc-server:8080
      - GRPC_STUDENT_COURSE_URL=grpc-server:8080
      - REST_API_URL=http://kafka-producer:8090/api/kafka/send
    depends_on:
      - grpc-server
    networks:
      - app-network
    volumes:
      - .env:/app/.env

  grpc-server:
    # image: my-grpc-server-image
    # container_name: grpc-server
    build:
      context: ../grpc-service/GrpcService/GrpcService/
      dockerfile: Dockerfile
    container_name: grpc-server
    restart: always
    ports:
      - "8000:8080"
    networks:
      - app-network

  kafka-producer:
      build:
        context: ../kafka-productor/
        dockerfile: Dockerfile
      container_name: kafka-producer
      restart: always
      ports:
        - "8090:8090"
      networks:
        - app-network

networks:
  app-network:
    driver: bridge
