services:
  app:
    build:
      context: ./app  
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    env_file:
      - ./app/.env  
    volumes:
      - ./app:/app    
      - /app/node_modules
