version: '3.8'

services:
  api:
    build: .
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Auth0__Domain=https://dev-q7eednrlae4yxvel.us.auth0.com/
      - Auth0__Audience=https://auth0APIKevin
      - Auth0__client_id=Dcqawg99cWzahtkyavoY5nC3uq35aUDt
      - Auth0__client_secret =60YCBP0JzvzmJr2qAHkOiF2yGdDCsgyBqYj3dKEgrBLtBaHZunnchbVi7kIMaE7Z
      - Auth0__grant_type=client_credentials
      - ASPNETCORE_PORT=8082
      