version: '3.8'

services:
  api:
    build: .
    ports:
      - "8082:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Auth0__Domain=dominio
      - Auth0__Audience=Audience
      - ASPNETCORE_PORT=8082
      